
DROP TABLE ZCOM99011;



DROP TABLE ZCOM99010;



DROP TABLE ZCOM99022;



DROP TABLE ZCOM99021;



DROP TABLE ZCOM99020;



DROP TABLE ZCOM99040;



DROP TABLE ZCOM99030;



DROP TABLE ZCOM99000;



CREATE TABLE ZCOM99000
(
	GRP_CO_ID            VARCHAR(5) NOT NULL,
	GRP_CO_NM            VARCHAR(100) NULL,
	GRP_CO_CTT           VARCHAR(200) NULL,
	EFF_STA_DT           VARCHAR(8) NULL,
	EFF_END_DT           VARCHAR(8) NULL,
	DEL_YN               VARCHAR(1) NULL,
	REG_USER_NUM         VARCHAR(10) NULL,
	REG_IP               VARCHAR(20) NULL,
	REG_DTM              VARCHAR(14) NULL,
	UPD_USER_NUM         VARCHAR(10) NULL,
	UPD_IP               VARCHAR(20) NULL,
	UPD_DTM              VARCHAR(14) NULL
);



CREATE UNIQUE INDEX ZCOM99010_PK ON ZCOM99000
(
	GRP_CO_ID
);



ALTER TABLE ZCOM99000
ADD PRIMARY KEY (GRP_CO_ID);



CREATE TABLE ZCOM99010
(
	GRP_CD               VARCHAR(5) NOT NULL,
	GRP_CD_NM            VARCHAR(100) NULL,
	GRP_CD_CTT           VARCHAR(200) NULL,
	EFF_STA_DT           VARCHAR(8) NULL,
	EFF_END_DT           VARCHAR(8) NULL,
	DEL_YN               VARCHAR(1) NULL,
	REG_USER_NUM         VARCHAR(10) NULL,
	REG_IP               VARCHAR(20) NULL,
	REG_DTM              VARCHAR(14) NULL,
	UPD_USER_NUM         VARCHAR(10) NULL,
	UPD_IP               VARCHAR(20) NULL,
	UPD_DTM              VARCHAR(14) NULL
);



CREATE UNIQUE INDEX ZCOM99010_PK ON ZCOM99010
(
	GRP_CD
);



ALTER TABLE ZCOM99010
ADD PRIMARY KEY (GRP_CD);



CREATE TABLE ZCOM99011
(
	GRP_CD               VARCHAR(5) NOT NULL,
	CD                   VARCHAR(5) NOT NULL,
	CD_NM                VARCHAR(100) NULL,
	SER_NUM              NUMERIC(3) NULL,
	CD_CTT               VARCHAR(200) NULL,
	EFF_STA_DT           VARCHAR(8) NULL,
	EFF_END_DT           VARCHAR(8) NULL,
	DEL_YN               VARCHAR(1) NULL,
	REG_USER_NUM         VARCHAR(10) NULL,
	REG_IP               VARCHAR(20) NULL,
	REG_DTM              VARCHAR(14) NULL,
	UPD_USER_NUM         VARCHAR(10) NULL,
	UPD_IP               VARCHAR(20) NULL,
	UPD_DTM              VARCHAR(14) NULL
);



CREATE UNIQUE INDEX ZCOM99011_PK ON ZCOM99011
(
	GRP_CD,
	CD
);



ALTER TABLE ZCOM99011
ADD PRIMARY KEY (GRP_CD,CD);



CREATE TABLE ZCOM99020
(
	GRP_CO_ID            VARCHAR(5) NOT NULL,
	MENU_ID              VARCHAR(10) NOT NULL,
	MENU_NM              VARCHAR(40) NULL,
	MENU_LVL             NUMERIC(3) NULL,
	SER_NUM              NUMERIC(3) NULL,
	SUP_MENU_ID          VARCHAR(10) NULL,
	ACT_ID               VARCHAR(20) NULL,
	URL                  VARCHAR(200) NULL,
	MENU_CTT             VARCHAR(200) NULL,
	EFF_STA_DT           VARCHAR(8) NULL,
	EFF_END_DT           VARCHAR(8) NULL,
	DEL_YN               VARCHAR(1) NULL,
	REG_USER_NUM         VARCHAR(10) NULL,
	REG_IP               VARCHAR(20) NULL,
	REG_DTM              VARCHAR(14) NULL,
	UPD_USER_NUM         VARCHAR(10) NULL,
	UPD_IP               VARCHAR(20) NULL,
	UPD_DTM              VARCHAR(14) NULL
);



CREATE UNIQUE INDEX ZCOM99020_PK ON ZCOM99020
(
	GRP_CO_ID,
	MENU_ID
);



ALTER TABLE ZCOM99020
ADD PRIMARY KEY (GRP_CO_ID,MENU_ID);



CREATE TABLE ZCOM99021
(
	GRP_CO_ID            VARCHAR(5) NOT NULL,
	SER_NUM              NUMERIC(5) NOT NULL,
	MENU_AUTH_CD         VARCHAR(5) NULL,
	USER_AUTH_CD         VARCHAR(5) NULL,
	USER_NUM             VARCHAR(10) NULL,
	EFF_STA_DT           VARCHAR(8) NULL,
	EFF_END_DT           VARCHAR(8) NULL,
	DEL_YN               VARCHAR(1) NULL,
	REG_USER_NUM         VARCHAR(10) NULL,
	REG_IP               VARCHAR(20) NULL,
	REG_DTM              VARCHAR(14) NULL,
	UPD_USER_NUM         VARCHAR(10) NULL,
	UPD_IP               VARCHAR(20) NULL,
	UPD_DTM              VARCHAR(14) NULL
);



CREATE UNIQUE INDEX ZCOM99022_PK ON ZCOM99021
(
	GRP_CO_ID,
	SER_NUM
);



ALTER TABLE ZCOM99021
ADD PRIMARY KEY (GRP_CO_ID,SER_NUM);



CREATE TABLE ZCOM99022
(
	GRP_CO_ID            VARCHAR(5) NOT NULL,
	MENU_ID              VARCHAR(10) NOT NULL,
	SER_NUM              NUMERIC(5) NOT NULL,
	EFF_STA_DT           VARCHAR(8) NULL,
	EFF_END_DT           VARCHAR(8) NULL,
	DEL_YN               VARCHAR(1) NULL,
	REG_USER_NUM         VARCHAR(10) NULL,
	REG_IP               VARCHAR(20) NULL,
	REG_DTM              VARCHAR(14) NULL,
	UPD_USER_NUM         VARCHAR(10) NULL,
	UPD_IP               VARCHAR(20) NULL,
	UPD_DTM              VARCHAR(14) NULL
);



CREATE UNIQUE INDEX ZCOM99021_PK ON ZCOM99022
(
	GRP_CO_ID,
	MENU_ID,
	SER_NUM
);



ALTER TABLE ZCOM99022
ADD PRIMARY KEY (GRP_CO_ID,MENU_ID,SER_NUM);



CREATE TABLE ZCOM99030
(
	GRP_CO_ID            VARCHAR(5) NOT NULL,
	USER_NUM             VARCHAR(10) NOT NULL,
	USER_ID              VARCHAR(100) NULL,
	USER_NM              VARCHAR(40) NULL,
	USER_PWD             VARCHAR(20) NULL,
	USER_AUTH_CD         VARCHAR(5) NULL,
	DEPT_ID              VARCHAR(10) NULL,
	MBL_NUM              VARCHAR(20) NULL,
	PHON_NUM             VARCHAR(20) NULL,
	MAIL_ADDR            VARCHAR(200) NULL,
	ZIP_NUM              VARCHAR(5) NULL,
	ADDR                 VARCHAR(200) NULL,
	DTL_ADDR             VARCHAR(200) NULL,
	EFF_STA_DT           VARCHAR(8) NULL,
	EFF_END_DT           VARCHAR(8) NULL,
	DEL_YN               VARCHAR(1) NULL,
	REG_USER_NUM         VARCHAR(10) NULL,
	REG_IP               VARCHAR(20) NULL,
	REG_DTM              VARCHAR(14) NULL,
	UPD_USER_NUM         VARCHAR(10) NULL,
	UPD_IP               VARCHAR(20) NULL,
	UPD_DTM              VARCHAR(14) NULL
);



CREATE UNIQUE INDEX ZCOM99030_PK ON ZCOM99030
(
	GRP_CO_ID,
	USER_NUM
);



ALTER TABLE ZCOM99030
ADD PRIMARY KEY (GRP_CO_ID,USER_NUM);



CREATE TABLE ZCOM99040
(
	GRP_CO_ID            VARCHAR(5) NOT NULL,
	DEPT_ID              VARCHAR(10) NOT NULL,
	DEPT_NM              VARCHAR(40) NULL,
	DEPT_CTT             VARCHAR(200) NULL,
	SUP_DEPT_ID          VARCHAR(10) NULL,
	EFF_STA_DT           VARCHAR(8) NULL,
	EFF_END_DT           VARCHAR(8) NULL,
	DEL_YN               VARCHAR(1) NULL,
	REG_USER_NUM         VARCHAR(10) NULL,
	REG_IP               VARCHAR(20) NULL,
	REG_DTM              VARCHAR(14) NULL,
	UPD_USER_NUM         VARCHAR(10) NULL,
	UPD_IP               VARCHAR(20) NULL,
	UPD_DTM              VARCHAR(14) NULL
);



CREATE UNIQUE INDEX ZCOM99040_PK ON ZCOM99040
(
	GRP_CO_ID,
	DEPT_ID
);



ALTER TABLE ZCOM99040
ADD PRIMARY KEY (GRP_CO_ID,DEPT_ID);



ALERT TABLE ZCOM99000 COMMENT = '관리자_그룹사';

    ALTER TABLE ZCOM99000 MODIFY COLUMN GRP_CO_ID VARCHAR(5) NOT NULL COMMENT '그룹사 ID';
    ALTER TABLE ZCOM99000 MODIFY COLUMN GRP_CO_NM VARCHAR(100) NULL COMMENT '그룹사 명';
    ALTER TABLE ZCOM99000 MODIFY COLUMN GRP_CO_CTT VARCHAR(200) NULL COMMENT '그룹사 내용';
    ALTER TABLE ZCOM99000 MODIFY COLUMN EFF_STA_DT VARCHAR(8) NULL COMMENT '유효 시작 일자';
    ALTER TABLE ZCOM99000 MODIFY COLUMN EFF_END_DT VARCHAR(8) NULL COMMENT '유효 종료 일자';
    ALTER TABLE ZCOM99000 MODIFY COLUMN DEL_YN VARCHAR(1) NULL COMMENT '삭제 여부';
    ALTER TABLE ZCOM99000 MODIFY COLUMN REG_USER_NUM VARCHAR(10) NULL COMMENT '등록 사용자 번호';
    ALTER TABLE ZCOM99000 MODIFY COLUMN REG_IP VARCHAR(20) NULL COMMENT '등록 IP';
    ALTER TABLE ZCOM99000 MODIFY COLUMN REG_DTM VARCHAR(14) NULL COMMENT '등록 일시';
    ALTER TABLE ZCOM99000 MODIFY COLUMN UPD_USER_NUM VARCHAR(10) NULL COMMENT '수정 사용자 번호';
    ALTER TABLE ZCOM99000 MODIFY COLUMN UPD_IP VARCHAR(20) NULL COMMENT '수정 IP';
    ALTER TABLE ZCOM99000 MODIFY COLUMN UPD_DTM VARCHAR(14) NULL COMMENT '수정 일시';
    
ALERT TABLE ZCOM99010 COMMENT = '관리자_그룹코드';

    ALTER TABLE ZCOM99010 MODIFY COLUMN GRP_CD VARCHAR(5) NOT NULL COMMENT '그룹 코드';
    ALTER TABLE ZCOM99010 MODIFY COLUMN GRP_CD_NM VARCHAR(100) NULL COMMENT '그룹 코드 명';
    ALTER TABLE ZCOM99010 MODIFY COLUMN GRP_CD_CTT VARCHAR(200) NULL COMMENT '그룹 코드 내용';
    ALTER TABLE ZCOM99010 MODIFY COLUMN EFF_STA_DT VARCHAR(8) NULL COMMENT '유효 시작 일자';
    ALTER TABLE ZCOM99010 MODIFY COLUMN EFF_END_DT VARCHAR(8) NULL COMMENT '유효 종료 일자';
    ALTER TABLE ZCOM99010 MODIFY COLUMN DEL_YN VARCHAR(1) NULL COMMENT '삭제 여부';
    ALTER TABLE ZCOM99010 MODIFY COLUMN REG_USER_NUM VARCHAR(10) NULL COMMENT '등록 사용자 번호';
    ALTER TABLE ZCOM99010 MODIFY COLUMN REG_IP VARCHAR(20) NULL COMMENT '등록 IP';
    ALTER TABLE ZCOM99010 MODIFY COLUMN REG_DTM VARCHAR(14) NULL COMMENT '등록 일시';
    ALTER TABLE ZCOM99010 MODIFY COLUMN UPD_USER_NUM VARCHAR(10) NULL COMMENT '수정 사용자 번호';
    ALTER TABLE ZCOM99010 MODIFY COLUMN UPD_IP VARCHAR(20) NULL COMMENT '수정 IP';
    ALTER TABLE ZCOM99010 MODIFY COLUMN UPD_DTM VARCHAR(14) NULL COMMENT '수정 일시';
    
ALERT TABLE ZCOM99011 COMMENT = '관리자_코드';

    ALTER TABLE ZCOM99011 MODIFY COLUMN GRP_CD VARCHAR(5) NOT NULL COMMENT '그룹 코드';
    ALTER TABLE ZCOM99011 MODIFY COLUMN CD VARCHAR(5) NOT NULL COMMENT '코드';
    ALTER TABLE ZCOM99011 MODIFY COLUMN CD_NM VARCHAR(100) NULL COMMENT '코드 명';
    ALTER TABLE ZCOM99011 MODIFY COLUMN SER_NUM NUMERIC(3) NULL COMMENT '일련번호';
    ALTER TABLE ZCOM99011 MODIFY COLUMN CD_CTT VARCHAR(200) NULL COMMENT '코드 내용';
    ALTER TABLE ZCOM99011 MODIFY COLUMN EFF_STA_DT VARCHAR(8) NULL COMMENT '유효 시작 일자';
    ALTER TABLE ZCOM99011 MODIFY COLUMN EFF_END_DT VARCHAR(8) NULL COMMENT '유효 종료 일자';
    ALTER TABLE ZCOM99011 MODIFY COLUMN DEL_YN VARCHAR(1) NULL COMMENT '삭제 여부';
    ALTER TABLE ZCOM99011 MODIFY COLUMN REG_USER_NUM VARCHAR(10) NULL COMMENT '등록 사용자 번호';
    ALTER TABLE ZCOM99011 MODIFY COLUMN REG_IP VARCHAR(20) NULL COMMENT '등록 IP';
    ALTER TABLE ZCOM99011 MODIFY COLUMN REG_DTM VARCHAR(14) NULL COMMENT '등록 일시';
    ALTER TABLE ZCOM99011 MODIFY COLUMN UPD_USER_NUM VARCHAR(10) NULL COMMENT '수정 사용자 번호';
    ALTER TABLE ZCOM99011 MODIFY COLUMN UPD_IP VARCHAR(20) NULL COMMENT '수정 IP';
    ALTER TABLE ZCOM99011 MODIFY COLUMN UPD_DTM VARCHAR(14) NULL COMMENT '수정 일시';
    
ALERT TABLE ZCOM99020 COMMENT = '관리자_메뉴';

    ALTER TABLE ZCOM99020 MODIFY COLUMN GRP_CO_ID VARCHAR(5) NOT NULL COMMENT '그룹사 ID';
    ALTER TABLE ZCOM99020 MODIFY COLUMN MENU_ID VARCHAR(10) NOT NULL COMMENT '메뉴 ID';
    ALTER TABLE ZCOM99020 MODIFY COLUMN MENU_NM VARCHAR(40) NULL COMMENT '메뉴 명';
    ALTER TABLE ZCOM99020 MODIFY COLUMN MENU_LVL NUMERIC(3) NULL COMMENT '메뉴 레벨';
    ALTER TABLE ZCOM99020 MODIFY COLUMN SER_NUM NUMERIC(3) NULL COMMENT '일련번호';
    ALTER TABLE ZCOM99020 MODIFY COLUMN SUP_MENU_ID VARCHAR(10) NULL COMMENT '상위 메뉴 ID';
    ALTER TABLE ZCOM99020 MODIFY COLUMN ACT_ID VARCHAR(20) NULL COMMENT 'ACTION ID';
    ALTER TABLE ZCOM99020 MODIFY COLUMN URL VARCHAR(200) NULL COMMENT 'URL';
    ALTER TABLE ZCOM99020 MODIFY COLUMN MENU_CTT VARCHAR(200) NULL COMMENT '메뉴 내용';
    ALTER TABLE ZCOM99020 MODIFY COLUMN EFF_STA_DT VARCHAR(8) NULL COMMENT '유효 시작 일자';
    ALTER TABLE ZCOM99020 MODIFY COLUMN EFF_END_DT VARCHAR(8) NULL COMMENT '유효 종료 일자';
    ALTER TABLE ZCOM99020 MODIFY COLUMN DEL_YN VARCHAR(1) NULL COMMENT '삭제 여부';
    ALTER TABLE ZCOM99020 MODIFY COLUMN REG_USER_NUM VARCHAR(10) NULL COMMENT '등록 사용자 번호';
    ALTER TABLE ZCOM99020 MODIFY COLUMN REG_IP VARCHAR(20) NULL COMMENT '등록 IP';
    ALTER TABLE ZCOM99020 MODIFY COLUMN REG_DTM VARCHAR(14) NULL COMMENT '등록 일시';
    ALTER TABLE ZCOM99020 MODIFY COLUMN UPD_USER_NUM VARCHAR(10) NULL COMMENT '수정 사용자 번호';
    ALTER TABLE ZCOM99020 MODIFY COLUMN UPD_IP VARCHAR(20) NULL COMMENT '수정 IP';
    ALTER TABLE ZCOM99020 MODIFY COLUMN UPD_DTM VARCHAR(14) NULL COMMENT '수정 일시';
    
ALERT TABLE ZCOM99021 COMMENT = '관리자_메뉴권한';

    ALTER TABLE ZCOM99021 MODIFY COLUMN GRP_CO_ID VARCHAR(5) NOT NULL COMMENT '그룹사 ID';
    ALTER TABLE ZCOM99021 MODIFY COLUMN SER_NUM NUMERIC(5) NOT NULL COMMENT '일련번호';
    ALTER TABLE ZCOM99021 MODIFY COLUMN MENU_AUTH_CD VARCHAR(5) NULL COMMENT '메뉴 권한 코드';
    ALTER TABLE ZCOM99021 MODIFY COLUMN USER_AUTH_CD VARCHAR(5) NULL COMMENT '사용자 권한 코드';
    ALTER TABLE ZCOM99021 MODIFY COLUMN USER_NUM VARCHAR(10) NULL COMMENT '사용자 번호';
    ALTER TABLE ZCOM99021 MODIFY COLUMN EFF_STA_DT VARCHAR(8) NULL COMMENT '유효 시작 일자';
    ALTER TABLE ZCOM99021 MODIFY COLUMN EFF_END_DT VARCHAR(8) NULL COMMENT '유효 종료 일자';
    ALTER TABLE ZCOM99021 MODIFY COLUMN DEL_YN VARCHAR(1) NULL COMMENT '삭제 여부';
    ALTER TABLE ZCOM99021 MODIFY COLUMN REG_USER_NUM VARCHAR(10) NULL COMMENT '등록 사용자 번호';
    ALTER TABLE ZCOM99021 MODIFY COLUMN REG_IP VARCHAR(20) NULL COMMENT '등록 IP';
    ALTER TABLE ZCOM99021 MODIFY COLUMN REG_DTM VARCHAR(14) NULL COMMENT '등록 일시';
    ALTER TABLE ZCOM99021 MODIFY COLUMN UPD_USER_NUM VARCHAR(10) NULL COMMENT '수정 사용자 번호';
    ALTER TABLE ZCOM99021 MODIFY COLUMN UPD_IP VARCHAR(20) NULL COMMENT '수정 IP';
    ALTER TABLE ZCOM99021 MODIFY COLUMN UPD_DTM VARCHAR(14) NULL COMMENT '수정 일시';
    
ALERT TABLE ZCOM99022 COMMENT = '관리자_권한별메뉴';

    ALTER TABLE ZCOM99022 MODIFY COLUMN GRP_CO_ID VARCHAR(5) NOT NULL COMMENT '그룹사 ID';
    ALTER TABLE ZCOM99022 MODIFY COLUMN MENU_ID VARCHAR(10) NOT NULL COMMENT '메뉴 ID';
    ALTER TABLE ZCOM99022 MODIFY COLUMN SER_NUM NUMERIC(5) NOT NULL COMMENT '일련번호';
    ALTER TABLE ZCOM99022 MODIFY COLUMN EFF_STA_DT VARCHAR(8) NULL COMMENT '유효 시작 일자';
    ALTER TABLE ZCOM99022 MODIFY COLUMN EFF_END_DT VARCHAR(8) NULL COMMENT '유효 종료 일자';
    ALTER TABLE ZCOM99022 MODIFY COLUMN DEL_YN VARCHAR(1) NULL COMMENT '삭제 여부';
    ALTER TABLE ZCOM99022 MODIFY COLUMN REG_USER_NUM VARCHAR(10) NULL COMMENT '등록 사용자 번호';
    ALTER TABLE ZCOM99022 MODIFY COLUMN REG_IP VARCHAR(20) NULL COMMENT '등록 IP';
    ALTER TABLE ZCOM99022 MODIFY COLUMN REG_DTM VARCHAR(14) NULL COMMENT '등록 일시';
    ALTER TABLE ZCOM99022 MODIFY COLUMN UPD_USER_NUM VARCHAR(10) NULL COMMENT '수정 사용자 번호';
    ALTER TABLE ZCOM99022 MODIFY COLUMN UPD_IP VARCHAR(20) NULL COMMENT '수정 IP';
    ALTER TABLE ZCOM99022 MODIFY COLUMN UPD_DTM VARCHAR(14) NULL COMMENT '수정 일시';
    
ALERT TABLE ZCOM99030 COMMENT = '관리자_사용자';

    ALTER TABLE ZCOM99030 MODIFY COLUMN GRP_CO_ID VARCHAR(5) NOT NULL COMMENT '그룹사 ID';
    ALTER TABLE ZCOM99030 MODIFY COLUMN USER_NUM VARCHAR(10) NOT NULL COMMENT '사용자 번호';
    ALTER TABLE ZCOM99030 MODIFY COLUMN USER_ID VARCHAR(100) NULL COMMENT '사용자 ID';
    ALTER TABLE ZCOM99030 MODIFY COLUMN USER_NM VARCHAR(40) NULL COMMENT '사용자 명';
    ALTER TABLE ZCOM99030 MODIFY COLUMN USER_PWD VARCHAR(20) NULL COMMENT '사용자 비밀번호';
    ALTER TABLE ZCOM99030 MODIFY COLUMN USER_AUTH_CD VARCHAR(5) NULL COMMENT '사용자 권한 코드';
    ALTER TABLE ZCOM99030 MODIFY COLUMN DEPT_ID VARCHAR(10) NULL COMMENT '부서 ID';
    ALTER TABLE ZCOM99030 MODIFY COLUMN MBL_NUM VARCHAR(20) NULL COMMENT '모바일 번호';
    ALTER TABLE ZCOM99030 MODIFY COLUMN PHON_NUM VARCHAR(20) NULL COMMENT '전화 번호';
    ALTER TABLE ZCOM99030 MODIFY COLUMN MAIL_ADDR VARCHAR(200) NULL COMMENT '메일 주소';
    ALTER TABLE ZCOM99030 MODIFY COLUMN ZIP_NUM VARCHAR(5) NULL COMMENT '우편번호';
    ALTER TABLE ZCOM99030 MODIFY COLUMN ADDR VARCHAR(200) NULL COMMENT '주소';
    ALTER TABLE ZCOM99030 MODIFY COLUMN DTL_ADDR VARCHAR(200) NULL COMMENT '상세 주소';
    ALTER TABLE ZCOM99030 MODIFY COLUMN EFF_STA_DT VARCHAR(8) NULL COMMENT '유효 시작 일자';
    ALTER TABLE ZCOM99030 MODIFY COLUMN EFF_END_DT VARCHAR(8) NULL COMMENT '유효 종료 일자';
    ALTER TABLE ZCOM99030 MODIFY COLUMN DEL_YN VARCHAR(1) NULL COMMENT '삭제 여부';
    ALTER TABLE ZCOM99030 MODIFY COLUMN REG_USER_NUM VARCHAR(10) NULL COMMENT '등록 사용자 번호';
    ALTER TABLE ZCOM99030 MODIFY COLUMN REG_IP VARCHAR(20) NULL COMMENT '등록 IP';
    ALTER TABLE ZCOM99030 MODIFY COLUMN REG_DTM VARCHAR(14) NULL COMMENT '등록 일시';
    ALTER TABLE ZCOM99030 MODIFY COLUMN UPD_USER_NUM VARCHAR(10) NULL COMMENT '수정 사용자 번호';
    ALTER TABLE ZCOM99030 MODIFY COLUMN UPD_IP VARCHAR(20) NULL COMMENT '수정 IP';
    ALTER TABLE ZCOM99030 MODIFY COLUMN UPD_DTM VARCHAR(14) NULL COMMENT '수정 일시';
    
ALERT TABLE ZCOM99040 COMMENT = '관리자_부서';

    ALTER TABLE ZCOM99040 MODIFY COLUMN GRP_CO_ID VARCHAR(5) NOT NULL COMMENT '그룹사 ID';
    ALTER TABLE ZCOM99040 MODIFY COLUMN DEPT_ID VARCHAR(10) NOT NULL COMMENT '부서 ID';
    ALTER TABLE ZCOM99040 MODIFY COLUMN DEPT_NM VARCHAR(40) NULL COMMENT '부서 명';
    ALTER TABLE ZCOM99040 MODIFY COLUMN DEPT_CTT VARCHAR(200) NULL COMMENT '부서 내용';
    ALTER TABLE ZCOM99040 MODIFY COLUMN SUP_DEPT_ID VARCHAR(10) NULL COMMENT '상위 부서 ID';
    ALTER TABLE ZCOM99040 MODIFY COLUMN EFF_STA_DT VARCHAR(8) NULL COMMENT '유효 시작 일자';
    ALTER TABLE ZCOM99040 MODIFY COLUMN EFF_END_DT VARCHAR(8) NULL COMMENT '유효 종료 일자';
    ALTER TABLE ZCOM99040 MODIFY COLUMN DEL_YN VARCHAR(1) NULL COMMENT '삭제 여부';
    ALTER TABLE ZCOM99040 MODIFY COLUMN REG_USER_NUM VARCHAR(10) NULL COMMENT '등록 사용자 번호';
    ALTER TABLE ZCOM99040 MODIFY COLUMN REG_IP VARCHAR(20) NULL COMMENT '등록 IP';
    ALTER TABLE ZCOM99040 MODIFY COLUMN REG_DTM VARCHAR(14) NULL COMMENT '등록 일시';
    ALTER TABLE ZCOM99040 MODIFY COLUMN UPD_USER_NUM VARCHAR(10) NULL COMMENT '수정 사용자 번호';
    ALTER TABLE ZCOM99040 MODIFY COLUMN UPD_IP VARCHAR(20) NULL COMMENT '수정 IP';
    ALTER TABLE ZCOM99040 MODIFY COLUMN UPD_DTM VARCHAR(14) NULL COMMENT '수정 일시';
    



