
DROP TABLE BACR20100;



DROP TABLE BACR20040;



DROP TABLE BACR20030;



DROP TABLE BACR20020;



DROP TABLE BACR10100;



DROP TABLE BACR20011;



DROP TABLE BACR20010;



CREATE TABLE BACR10100
(
	PVL_ID               VARCHAR(5) NOT NULL,
	MB_NUM               VARCHAR(10) NOT NULL,
	MB_ID                VARCHAR(100) NULL,
	MB_NM                VARCHAR(40) NULL,
	MB_PWD               VARCHAR(20) NULL,
	BTD                  VARCHAR(8) NULL,
	MBL_NUM              VARCHAR(20) NULL,
	MAIL_ADDR            VARCHAR(200) NULL,
	GD_CD                VARCHAR(5) NULL,
	EFF_STA_DT           VARCHAR(8) NULL,
	EFF_END_DT           VARCHAR(8) NULL,
	DEL_YN               VARCHAR(1) NULL,
	REG_USER_NUM         VARCHAR(10) NULL,
	REG_IP               VARCHAR(20) NULL,
	REG_DTM              VARCHAR(14) NULL,
	UPD_USER_NUM         VARCHAR(10) NULL,
	UPD_IP               VARCHAR(20) NULL,
	UPD_DTM              VARCHAR(14) NULL
);



CREATE UNIQUE INDEX BACR10100_PK ON BACR10100
(
	PVL_ID,
	MB_NUM
);



ALTER TABLE BACR10100
ADD PRIMARY KEY (PVL_ID,MB_NUM);



CREATE TABLE BACR20010
(
	TNMT_ID              VARCHAR(20) NOT NULL,
	TNMT_NM              VARCHAR(100) NULL,
	PWD                  VARCHAR(20) NULL,
	TNMT_PVL_ID          VARCHAR(5) NULL,
	TNMT_CL_CD           VARCHAR(5) NULL,
	SP_CNT               NUMERIC(3) NULL,
	SOON_CNT             NUMERIC(3) NULL,
	SI_CNT               NUMERIC(3) NULL,
	STA_DT               VARCHAR(8) NULL,
	END_DT               VARCHAR(8) NULL,
	DEL_YN               VARCHAR(1) NULL,
	REG_USER_NUM         VARCHAR(10) NULL,
	REG_IP               VARCHAR(20) NULL,
	REG_DTM              VARCHAR(14) NULL,
	UPD_USER_NUM         VARCHAR(10) NULL,
	UPD_IP               VARCHAR(20) NULL,
	UPD_DTM              VARCHAR(14) NULL
);



CREATE UNIQUE INDEX BACR20010_PK ON BACR20010
(
	TNMT_ID
);



ALTER TABLE BACR20010
ADD PRIMARY KEY (TNMT_ID);



CREATE TABLE BACR20011
(
	TNMT_ID              VARCHAR(20) NOT NULL,
	SP_CL_CD             VARCHAR(5) NOT NULL,
	SP_SER_NUM           NUMERIC(3) NOT NULL,
	SP_NM                VARCHAR(40) NULL,
	REG_USER_NUM         VARCHAR(10) NULL,
	REG_IP               VARCHAR(20) NULL,
	REG_DTM              VARCHAR(14) NULL
);



CREATE UNIQUE INDEX BACR20011_PK ON BACR20011
(
	TNMT_ID,
	SP_CL_CD,
	SP_SER_NUM
);



ALTER TABLE BACR20011
ADD PRIMARY KEY (TNMT_ID,SP_CL_CD,SP_SER_NUM);



CREATE TABLE BACR20020
(
	TNMT_ID              VARCHAR(20) NOT NULL,
	CPT_CL_CD            VARCHAR(5) NOT NULL,
	DEL_YN               VARCHAR(1) NULL,
	REG_USER_NUM         VARCHAR(10) NULL,
	REG_IP               VARCHAR(20) NULL,
	REG_DTM              VARCHAR(14) NULL,
	UPD_USER_NUM         VARCHAR(10) NULL,
	UPD_IP               VARCHAR(20) NULL,
	UPD_DTM              VARCHAR(14) NULL
);



CREATE UNIQUE INDEX BACR20020_PK ON BACR20020
(
	TNMT_ID,
	CPT_CL_CD
);



ALTER TABLE BACR20020
ADD PRIMARY KEY (TNMT_ID,CPT_CL_CD);



CREATE TABLE BACR20030
(
	TNMT_ID              VARCHAR(20) NOT NULL,
	CPT_CL_CD            VARCHAR(5) NOT NULL,
	GRP_SER_NUM          NUMERIC(5) NOT NULL,
	CPT_GRP_NM           VARCHAR(100) NULL,
	DEL_YN               VARCHAR(1) NULL,
	REG_USER_NUM         VARCHAR(10) NULL,
	REG_IP               VARCHAR(20) NULL,
	REG_DTM              VARCHAR(14) NULL,
	UPD_USER_NUM         VARCHAR(10) NULL,
	UPD_IP               VARCHAR(20) NULL,
	UPD_DTM              VARCHAR(14) NULL
);



CREATE UNIQUE INDEX BACR20030_PK ON BACR20030
(
	TNMT_ID,
	CPT_CL_CD,
	GRP_SER_NUM
);



ALTER TABLE BACR20030
ADD PRIMARY KEY (TNMT_ID,CPT_CL_CD,GRP_SER_NUM);



CREATE TABLE BACR20040
(
	TNMT_ID              VARCHAR(20) NOT NULL,
	CPT_CL_CD            VARCHAR(5) NOT NULL,
	GRP_SER_NUM          NUMERIC(5) NOT NULL,
	MB_NUM               VARCHAR(10) NOT NULL,
	PVL_ID               VARCHAR(5) NOT NULL,
	DEL_YN               VARCHAR(1) NULL,
	REG_USER_NUM         VARCHAR(10) NULL,
	REG_IP               VARCHAR(20) NULL,
	REG_DTM              VARCHAR(14) NULL,
	UPD_USER_NUM         VARCHAR(10) NULL,
	UPD_IP               VARCHAR(20) NULL,
	UPD_DTM              VARCHAR(14) NULL
);



CREATE UNIQUE INDEX BACR20040_PK ON BACR20040
(
	TNMT_ID,
	CPT_CL_CD,
	GRP_SER_NUM,
	MB_NUM,
	PVL_ID
);



ALTER TABLE BACR20040
ADD PRIMARY KEY (TNMT_ID,CPT_CL_CD,GRP_SER_NUM,MB_NUM,PVL_ID);



CREATE TABLE BACR20100
(
	TNMT_ID              VARCHAR(20) NOT NULL,
	CPT_CL_CD            VARCHAR(5) NOT NULL,
	GRP_SER_NUM          NUMERIC(5) NOT NULL,
	MB_NUM               VARCHAR(10) NOT NULL,
	SC_SER_NUM           CHAR(18) NOT NULL,
	PVL_ID               VARCHAR(5) NOT NULL,
	SP_NUM               NUMERIC(3) NULL,
	SOON_NUM             NUMERIC(3) NULL,
	SI_NUM               NUMERIC(3) NULL,
	SC                   NUMERIC(3) NULL,
	REG_USER_NUM         VARCHAR(10) NULL,
	REG_IP               VARCHAR(20) NULL,
	REG_DTM              VARCHAR(14) NULL,
	UPD_USER_NUM         VARCHAR(10) NULL,
	UPD_IP               VARCHAR(20) NULL,
	UPD_DTM              VARCHAR(14) NULL
);



CREATE UNIQUE INDEX BACR20100_PK ON BACR20100
(
	TNMT_ID,
	CPT_CL_CD,
	GRP_SER_NUM,
	MB_NUM,
	SC_SER_NUM,
	PVL_ID
);



ALTER TABLE BACR20100
ADD PRIMARY KEY (TNMT_ID,CPT_CL_CD,GRP_SER_NUM,MB_NUM,SC_SER_NUM,PVL_ID);



ALERT TABLE BACR10100 COMMENT = '기본정보_회원';

    ALTER TABLE BACR10100 MODIFY COLUMN PVL_ID VARCHAR(5) NOT NULL COMMENT '정 ID';
    ALTER TABLE BACR10100 MODIFY COLUMN MB_NUM VARCHAR(10) NOT NULL COMMENT '회원 번호';
    ALTER TABLE BACR10100 MODIFY COLUMN MB_ID VARCHAR(100) NULL COMMENT '회원 ID';
    ALTER TABLE BACR10100 MODIFY COLUMN MB_NM VARCHAR(40) NULL COMMENT '회원 명';
    ALTER TABLE BACR10100 MODIFY COLUMN MB_PWD VARCHAR(20) NULL COMMENT '회원 비밀번호';
    ALTER TABLE BACR10100 MODIFY COLUMN BTD VARCHAR(8) NULL COMMENT '생년월일';
    ALTER TABLE BACR10100 MODIFY COLUMN MBL_NUM VARCHAR(20) NULL COMMENT '모바일 번호';
    ALTER TABLE BACR10100 MODIFY COLUMN MAIL_ADDR VARCHAR(200) NULL COMMENT '메일 주소';
    ALTER TABLE BACR10100 MODIFY COLUMN GD_CD VARCHAR(5) NULL COMMENT '성별 코드';
    ALTER TABLE BACR10100 MODIFY COLUMN EFF_STA_DT VARCHAR(8) NULL COMMENT '유효 시작 일자';
    ALTER TABLE BACR10100 MODIFY COLUMN EFF_END_DT VARCHAR(8) NULL COMMENT '유효 종료 일자';
    ALTER TABLE BACR10100 MODIFY COLUMN DEL_YN VARCHAR(1) NULL COMMENT '삭제 여부';
    ALTER TABLE BACR10100 MODIFY COLUMN REG_USER_NUM VARCHAR(10) NULL COMMENT '등록 사용자 번호';
    ALTER TABLE BACR10100 MODIFY COLUMN REG_IP VARCHAR(20) NULL COMMENT '등록 IP';
    ALTER TABLE BACR10100 MODIFY COLUMN REG_DTM VARCHAR(14) NULL COMMENT '등록 일시';
    ALTER TABLE BACR10100 MODIFY COLUMN UPD_USER_NUM VARCHAR(10) NULL COMMENT '수정 사용자 번호';
    ALTER TABLE BACR10100 MODIFY COLUMN UPD_IP VARCHAR(20) NULL COMMENT '수정 IP';
    ALTER TABLE BACR10100 MODIFY COLUMN UPD_DTM VARCHAR(14) NULL COMMENT '수정 일시';
    
ALERT TABLE BACR20010 COMMENT = '대회_대회';

    ALTER TABLE BACR20010 MODIFY COLUMN TNMT_ID VARCHAR(20) NOT NULL COMMENT '대회 ID';
    ALTER TABLE BACR20010 MODIFY COLUMN TNMT_NM VARCHAR(100) NULL COMMENT '대회 명';
    ALTER TABLE BACR20010 MODIFY COLUMN PWD VARCHAR(20) NULL COMMENT '비밀번호';
    ALTER TABLE BACR20010 MODIFY COLUMN TNMT_PVL_ID VARCHAR(5) NULL COMMENT '대회 정 ID';
    ALTER TABLE BACR20010 MODIFY COLUMN TNMT_CL_CD VARCHAR(5) NULL COMMENT '대회 구분 코드';
    ALTER TABLE BACR20010 MODIFY COLUMN SP_CNT NUMERIC(3) NULL COMMENT '사대 수';
    ALTER TABLE BACR20010 MODIFY COLUMN SOON_CNT NUMERIC(3) NULL COMMENT '순 수';
    ALTER TABLE BACR20010 MODIFY COLUMN SI_CNT NUMERIC(3) NULL COMMENT '시 수';
    ALTER TABLE BACR20010 MODIFY COLUMN STA_DT VARCHAR(8) NULL COMMENT '시작 일자';
    ALTER TABLE BACR20010 MODIFY COLUMN END_DT VARCHAR(8) NULL COMMENT '종료 일자';
    ALTER TABLE BACR20010 MODIFY COLUMN DEL_YN VARCHAR(1) NULL COMMENT '삭제 여부';
    ALTER TABLE BACR20010 MODIFY COLUMN REG_USER_NUM VARCHAR(10) NULL COMMENT '등록 사용자 번호';
    ALTER TABLE BACR20010 MODIFY COLUMN REG_IP VARCHAR(20) NULL COMMENT '등록 IP';
    ALTER TABLE BACR20010 MODIFY COLUMN REG_DTM VARCHAR(14) NULL COMMENT '등록 일시';
    ALTER TABLE BACR20010 MODIFY COLUMN UPD_USER_NUM VARCHAR(10) NULL COMMENT '수정 사용자 번호';
    ALTER TABLE BACR20010 MODIFY COLUMN UPD_IP VARCHAR(20) NULL COMMENT '수정 IP';
    ALTER TABLE BACR20010 MODIFY COLUMN UPD_DTM VARCHAR(14) NULL COMMENT '수정 일시';
    
ALERT TABLE BACR20011 COMMENT = '대회_사대';

    ALTER TABLE BACR20011 MODIFY COLUMN TNMT_ID VARCHAR(20) NOT NULL COMMENT '대회 ID';
    ALTER TABLE BACR20011 MODIFY COLUMN SP_CL_CD VARCHAR(5) NOT NULL COMMENT '사대 구분 코드';
    ALTER TABLE BACR20011 MODIFY COLUMN SP_SER_NUM NUMERIC(3) NOT NULL COMMENT '사대 일련번호';
    ALTER TABLE BACR20011 MODIFY COLUMN SP_NM VARCHAR(40) NULL COMMENT '사대 명';
    ALTER TABLE BACR20011 MODIFY COLUMN REG_USER_NUM VARCHAR(10) NULL COMMENT '등록 사용자 번호';
    ALTER TABLE BACR20011 MODIFY COLUMN REG_IP VARCHAR(20) NULL COMMENT '등록 IP';
    ALTER TABLE BACR20011 MODIFY COLUMN REG_DTM VARCHAR(14) NULL COMMENT '등록 일시';
    
ALERT TABLE BACR20020 COMMENT = '대회_참가구분';

    ALTER TABLE BACR20020 MODIFY COLUMN TNMT_ID VARCHAR(20) NOT NULL COMMENT '대회 ID';
    ALTER TABLE BACR20020 MODIFY COLUMN CPT_CL_CD VARCHAR(5) NOT NULL COMMENT '참가 구분 코드';
    ALTER TABLE BACR20020 MODIFY COLUMN DEL_YN VARCHAR(1) NULL COMMENT '삭제 여부';
    ALTER TABLE BACR20020 MODIFY COLUMN REG_USER_NUM VARCHAR(10) NULL COMMENT '등록 사용자 번호';
    ALTER TABLE BACR20020 MODIFY COLUMN REG_IP VARCHAR(20) NULL COMMENT '등록 IP';
    ALTER TABLE BACR20020 MODIFY COLUMN REG_DTM VARCHAR(14) NULL COMMENT '등록 일시';
    ALTER TABLE BACR20020 MODIFY COLUMN UPD_USER_NUM VARCHAR(10) NULL COMMENT '수정 사용자 번호';
    ALTER TABLE BACR20020 MODIFY COLUMN UPD_IP VARCHAR(20) NULL COMMENT '수정 IP';
    ALTER TABLE BACR20020 MODIFY COLUMN UPD_DTM VARCHAR(14) NULL COMMENT '수정 일시';
    
ALERT TABLE BACR20030 COMMENT = '대회_참가그룹';

    ALTER TABLE BACR20030 MODIFY COLUMN TNMT_ID VARCHAR(20) NOT NULL COMMENT '대회 ID';
    ALTER TABLE BACR20030 MODIFY COLUMN CPT_CL_CD VARCHAR(5) NOT NULL COMMENT '참가 구분 코드';
    ALTER TABLE BACR20030 MODIFY COLUMN GRP_SER_NUM NUMERIC(5) NOT NULL COMMENT '그룹 일련번호';
    ALTER TABLE BACR20030 MODIFY COLUMN CPT_GRP_NM VARCHAR(100) NULL COMMENT '참가 그룹 명';
    ALTER TABLE BACR20030 MODIFY COLUMN DEL_YN VARCHAR(1) NULL COMMENT '삭제 여부';
    ALTER TABLE BACR20030 MODIFY COLUMN REG_USER_NUM VARCHAR(10) NULL COMMENT '등록 사용자 번호';
    ALTER TABLE BACR20030 MODIFY COLUMN REG_IP VARCHAR(20) NULL COMMENT '등록 IP';
    ALTER TABLE BACR20030 MODIFY COLUMN REG_DTM VARCHAR(14) NULL COMMENT '등록 일시';
    ALTER TABLE BACR20030 MODIFY COLUMN UPD_USER_NUM VARCHAR(10) NULL COMMENT '수정 사용자 번호';
    ALTER TABLE BACR20030 MODIFY COLUMN UPD_IP VARCHAR(20) NULL COMMENT '수정 IP';
    ALTER TABLE BACR20030 MODIFY COLUMN UPD_DTM VARCHAR(14) NULL COMMENT '수정 일시';
    
ALERT TABLE BACR20040 COMMENT = '대회_참가자';

    ALTER TABLE BACR20040 MODIFY COLUMN TNMT_ID VARCHAR(20) NOT NULL COMMENT '대회 ID';
    ALTER TABLE BACR20040 MODIFY COLUMN CPT_CL_CD VARCHAR(5) NOT NULL COMMENT '참가 구분 코드';
    ALTER TABLE BACR20040 MODIFY COLUMN GRP_SER_NUM NUMERIC(5) NOT NULL COMMENT '그룹 일련번호';
    ALTER TABLE BACR20040 MODIFY COLUMN MB_NUM VARCHAR(10) NOT NULL COMMENT '회원 번호';
    ALTER TABLE BACR20040 MODIFY COLUMN PVL_ID VARCHAR(5) NOT NULL COMMENT '정 ID';
    ALTER TABLE BACR20040 MODIFY COLUMN DEL_YN VARCHAR(1) NULL COMMENT '삭제 여부';
    ALTER TABLE BACR20040 MODIFY COLUMN REG_USER_NUM VARCHAR(10) NULL COMMENT '등록 사용자 번호';
    ALTER TABLE BACR20040 MODIFY COLUMN REG_IP VARCHAR(20) NULL COMMENT '등록 IP';
    ALTER TABLE BACR20040 MODIFY COLUMN REG_DTM VARCHAR(14) NULL COMMENT '등록 일시';
    ALTER TABLE BACR20040 MODIFY COLUMN UPD_USER_NUM VARCHAR(10) NULL COMMENT '수정 사용자 번호';
    ALTER TABLE BACR20040 MODIFY COLUMN UPD_IP VARCHAR(20) NULL COMMENT '수정 IP';
    ALTER TABLE BACR20040 MODIFY COLUMN UPD_DTM VARCHAR(14) NULL COMMENT '수정 일시';
    
ALERT TABLE BACR20100 COMMENT = '대회_점수';

    ALTER TABLE BACR20100 MODIFY COLUMN TNMT_ID VARCHAR(20) NOT NULL COMMENT '대회 ID';
    ALTER TABLE BACR20100 MODIFY COLUMN CPT_CL_CD VARCHAR(5) NOT NULL COMMENT '참가 구분 코드';
    ALTER TABLE BACR20100 MODIFY COLUMN GRP_SER_NUM NUMERIC(5) NOT NULL COMMENT '그룹 일련번호';
    ALTER TABLE BACR20100 MODIFY COLUMN MB_NUM VARCHAR(10) NOT NULL COMMENT '회원 번호';
    ALTER TABLE BACR20100 MODIFY COLUMN SC_SER_NUM CHAR(18) NOT NULL COMMENT '점수 일련번호';
    ALTER TABLE BACR20100 MODIFY COLUMN PVL_ID VARCHAR(5) NOT NULL COMMENT '정 ID';
    ALTER TABLE BACR20100 MODIFY COLUMN SP_NUM NUMERIC(3) NULL COMMENT '사대 번호';
    ALTER TABLE BACR20100 MODIFY COLUMN SOON_NUM NUMERIC(3) NULL COMMENT '순 번호';
    ALTER TABLE BACR20100 MODIFY COLUMN SI_NUM NUMERIC(3) NULL COMMENT '시 번호';
    ALTER TABLE BACR20100 MODIFY COLUMN SC NUMERIC(3) NULL COMMENT '점수';
    ALTER TABLE BACR20100 MODIFY COLUMN REG_USER_NUM VARCHAR(10) NULL COMMENT '등록 사용자 번호';
    ALTER TABLE BACR20100 MODIFY COLUMN REG_IP VARCHAR(20) NULL COMMENT '등록 IP';
    ALTER TABLE BACR20100 MODIFY COLUMN REG_DTM VARCHAR(14) NULL COMMENT '등록 일시';
    ALTER TABLE BACR20100 MODIFY COLUMN UPD_USER_NUM VARCHAR(10) NULL COMMENT '수정 사용자 번호';
    ALTER TABLE BACR20100 MODIFY COLUMN UPD_IP VARCHAR(20) NULL COMMENT '수정 IP';
    ALTER TABLE BACR20100 MODIFY COLUMN UPD_DTM VARCHAR(14) NULL COMMENT '수정 일시';
    



